"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import AuthGuard from "@/components/AuthGuard";
import Shell from "@/components/Shell";
import { api } from "@/lib/api";

type Vendor={id:string;project_id:string;vendor_code:string;vendor_name:string;category:string;contact_name?:string|null;contact_email?:string|null;status:string;quality_score:number;delivery_score:number;documentation_score:number;inspection_score:number;ncr_count:number;overall_score:number;notes?:string|null;updated_at:string};
type Project={id:string;code:string;name:string};

export default function VendorDetailPage(){
 const {id}=useParams<{id:string}>(); const [item,setItem]=useState<Vendor|null>(null); const [project,setProject]=useState<Project|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{if(!id)return;api<Vendor>(`/vendors/${id}`).then(async v=>{setItem(v);const ps=await api<Project[]>("/projects");setProject(ps.find(p=>p.id===v.project_id)||null)}).catch(e=>setError(e instanceof Error?e.message:"Failed to load vendor"))},[id]);
 function setField(name:keyof Vendor,value:string|number){setItem(p=>p?{...p,[name]:value}:p)}
 async function save(e:FormEvent){e.preventDefault();if(!item)return;setSaving(true);setError("");try{const updated=await api<Vendor>(`/vendors/${id}`,{method:"PATCH",body:JSON.stringify({vendor_name:item.vendor_name,category:item.category,contact_name:item.contact_name||null,contact_email:item.contact_email||null,status:item.status,quality_score:Number(item.quality_score),delivery_score:Number(item.delivery_score),documentation_score:Number(item.documentation_score),inspection_score:Number(item.inspection_score),ncr_count:Number(item.ncr_count),notes:item.notes||null})});setItem(updated)}catch(e){setError(e instanceof Error?e.message:"Failed to update vendor")}finally{setSaving(false)}}
 const predicted=item?Math.max(0,Math.min(100,item.quality_score*.35+item.delivery_score*.20+item.documentation_score*.20+item.inspection_score*.25-Math.min(item.ncr_count*2,20))):0;
 const statusClass=item?.status==="APPROVED"?"workflow-approved":item?.status==="WATCHLIST"?"workflow-in_review":"workflow-rejected";
 return <AuthGuard><Shell><div className="page-head"><div><p className="eyebrow">Vendor Assurance</p><h1>{item?.vendor_name||"Vendor Detail"}</h1><p className="muted">{item?`${item.vendor_code} · ${item.category}`:"Loading vendor..."}</p></div><div className="head-actions">{project?<Link className="secondary-btn" href={`/projects/${project.id}`}>Project Workspace</Link>:null}<Link className="secondary-btn" href={`/vendors${item?`?project_id=${encodeURIComponent(item.project_id)}`:""}`}>← Vendor Quality</Link></div></div>
 {error?<div className="error">{error}</div>:null}{!item?<p className="muted">Loading vendor...</p>:<><div className="grid inspection-summary"><div className="card"><div className="muted">Overall Score</div><div className="metric">{item.overall_score.toFixed(1)}</div></div><div className="card"><div className="muted">Status</div><div className="metric metric-small"><span className={`workflow ${statusClass}`}>{item.status}</span></div></div><div className="card"><div className="muted">NCR Count</div><div className="metric">{item.ncr_count}</div></div><div className="card"><div className="muted">Projected Score</div><div className="metric">{predicted.toFixed(1)}</div></div></div>
 <form className="card form-card section-card" onSubmit={save}><div className="toolbar"><div><h2>Vendor Performance</h2><p className="muted small">Weighted score: Quality 35%, Delivery 20%, Documentation 20%, Inspection 25%, minus NCR penalty.</p></div></div><div className="form-grid">
 <label><span>Vendor Code</span><input disabled value={item.vendor_code}/></label><label><span>Status</span><select value={item.status} onChange={e=>setField("status",e.target.value)}><option>APPROVED</option><option>WATCHLIST</option><option>SUSPENDED</option></select></label>
 <label className="full-field"><span>Vendor Name *</span><input required value={item.vendor_name} onChange={e=>setField("vendor_name",e.target.value)}/></label><label><span>Category</span><input value={item.category} onChange={e=>setField("category",e.target.value)}/></label><label><span>Contact Name</span><input value={item.contact_name||""} onChange={e=>setField("contact_name",e.target.value)}/></label><label><span>Contact Email</span><input type="email" value={item.contact_email||""} onChange={e=>setField("contact_email",e.target.value)}/></label>
 <Score label="Quality Score" value={item.quality_score} set={v=>setField("quality_score",v)}/><Score label="Delivery Score" value={item.delivery_score} set={v=>setField("delivery_score",v)}/><Score label="Documentation Score" value={item.documentation_score} set={v=>setField("documentation_score",v)}/><Score label="Inspection Score" value={item.inspection_score} set={v=>setField("inspection_score",v)}/><label><span>NCR Count</span><input type="number" min="0" value={item.ncr_count} onChange={e=>setField("ncr_count",Number(e.target.value))}/></label>
 <label className="full-field"><span>Notes</span><textarea rows={6} value={item.notes||""} onChange={e=>setField("notes",e.target.value)}/></label></div><div className="form-actions"><button className="btn-action" disabled={saving}>{saving?"Saving...":"Save Changes"}</button></div></form></>}</Shell></AuthGuard>
}
function Score({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label><span>{label}</span><input type="number" min="0" max="100" value={value} onChange={e=>set(Number(e.target.value))}/></label>}
